alias ls='ls -l'
alias ll='ls -lahrt'
alias h='history'
alias p='ps aux'
alias scp='scp -C'
alias sudo='command sudo '
alias g='git'
alias less='less -R'
alias pg='pgrep -fli'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
